#Quarkus Platform - GoogleCloudServices - Quarkus Platform Properties
platform.release-info@${platform.key}$${platform.stream}\#${platform.release}=com.redhat.quarkus.platform\:quarkus-bom\:\:pom\:2.2.3.Camel-temporary-redhat-0001,com.redhat.quarkus.platform\:quarkus-camel-bom\:\:pom\:2.2.3.Camel-temporary-redhat-0001
