#Quarkus Platform - Cassandra - Quarkus Platform Properties
platform.release-info@${platform.key}$${platform.stream}\#${platform.release}=com.redhat.quarkus.platform\:quarkus-bom\:\:pom\:999-SNAPSHOT-redhat-00001
